### ISSUE TITLE
install.sh 오류 제보

### ISSUE THREAD

**Issue by singleheart** [jason9693/oslo-kogpt-finetunig#1]
안녕하세요, OSLO를 활용할 간편한 예제를 만들어 주셔서 감사합니다. 
여기 코드를 받아 설치하고 실행하다가 오류를 발견해서 제보 드립니다. 

https://github.com/jason9693/oslo-kogpt-finetunig/blob/e6036aa1f56c083801536a4a4e2ac18162a3398d/install.sh#L2
이 코드는 oslo가 설치된 디렉토리에서 실행해야 잘 작동합니다. 

아래와 같이 고치면 좋을 것 같습니다:
```
git clone https://github.com/tunib-ai/oslo.git

cd oslo
git checkout 85a4ff11816f8319a7344f1e596dd6b3e7592034
pip install --editable .
```

이렇게 수정해서 설치하고 README의 싱글노드 예제를 실행하니 잘 작동했습니다.

**Comment by jason9693** [comment]
오류제보 감사합니다1!
